server:
  port: 9527
spring:
  application:
    name: ngroute-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: server_routh #路由的id 没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9001 #匹配后提供服务的路由地址
          #uri: lb://ngroute-server #匹配后提供服务的路由地址
          predicates:
          - Path=/algorithm/** #断言，路径相匹配的进行路由
          - After=2021-08-09T22:22:32.262+08:00[GMT+08:00]
#          - Cookie=username,zzyy
          - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性并且值为整数的正则表达式
        - id: server_routh2 #路由的id 没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9002 #匹配后提供服务的路由地址
          #uri: lb://ngroute-server #匹配后提供服务的路由地址
          predicates:
          - Path=/algorithm/** #断言，路径相匹配的进行路由
          - After=2021-08-09T22:22:32.262+08:00[GMT+08:00]
          - Cookie=username,zzyy
